<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <!-- ensures every link below opens in a new tab similar to HTML target="_blank" -->
    <base target="_blank" />

    <h2 id="introduction"><a href="#introduction">✨ INTRODUCTION</a></h2>
    <p>
      In this course, I will be guiding you step by step through how to build and deploy AI powered chatbot like ChatGPT
      using Svelte, Sveltkit (for Frontend), ExpressJs (for Backend) and Openai API.
    </p>
    <p>Then deploy the AI chatbot app to Vercel (Frontend hosting) and Render (Backend hosting) ❤.</p>
    <h3 id="meet-course-instructor"><a href="#meet-course-instructor">🧑‍💻 Meet Course Instructor</a></h3>
    <p>
      <strong>i. Full name</strong>
      :
      <a
        href="https://github.com/SolomonFoskaay?ref=AiHiPUniversity.com"
        rel="external"
        title="Solomon Foskaay Github Profile">
        Solomon Foskaay
      </a>
    </p>
    <p>
      <strong>ii. Experience</strong>
      : 12Years in IT (as a Web designer (Wordpress), Digital Marketing &amp; SEO expert, Web3/Crypto Researcher and now
      AI/Game/Metaverse/Web2/Web3 Developer Instructor)
    </p>
    <h3 id="course-prerequisites-for-taking-this-course">
      <a href="#course-prerequisites-for-taking-this-course">🛂 Course Prerequisites for taking this course</a>
    </h3>
    <p>Prerequisites for taking this course:</p>
    <p>
      <strong>i</strong>
       Nodejs (Install if not having it yet latest LTS version) ii. Pnpm Node package (Install if not having it yet) iii.
      Essential Basic knowledge of: i- Using CLI ii- Git/Github iii- IDE/Code Editor like Visual Studio Code (VSCode) iv-
      Svelte/Sveltekit (frontend) v- ExpressJs (backend) vi- Web Hosting &amp; Domain Hosting iv. Optional Basic knowledge
      of: i- Openai large language AI models and their API ii- Vercel (frontend hosting) iii- Render (backend hosting)
    </p>
    <h2 id="video"><a href="#video">🎉 VIDEO</a></h2>
    <p>If you prefer to watch the video, then below is the full video. If not, continue to read the text format.</p>
    <h2 id="7-stable-diffusion-ai-image-generator">
      <a href="#7-stable-diffusion-ai-image-generator">📚 (7) Stable Diffusion AI Image Generator</a>
    </h2>
    <p>
      This Ai generates stable diffusion images that are gorgeous and pro with just basic instructions. making it
      useable by non-artist.
    </p>
    <ul>
      <li>
        <a
          href="https://starryai.com/stable-diffusion?ref=AiHiPUniversity.com"
          rel="external"
          title="Starryai Stable Diffusion Website">
          Starryai Stable Diffusion
        </a>
      </li>
    </ul>
    <h2 id="6-nft-art-generator-ai"><a href="#6-nft-art-generator-ai">🚀 (6) NFT Art Generator AI</a></h2>
    <p>These are Ai that generates NFT Arts.</p>
    <ul>
      <li>
        <a
          href="https://starryai.com/create-nft-art-with-artificial-intelligence?ref=AiHiPUniversity.com"
          rel="external"
          title="Starryai Art Ai Website">
          Starryai Art Ai
        </a>
      </li>
    </ul>
    <h2 id="5-avatar-generator-ai"><a href="#5-avatar-generator-ai">📚 (5) Avatar Generator AI</a></h2>
    <p>These are Ai that can help you to generate Avatars for your social media and profile picture.</p>
    <ul>
      <li>
        <a
          href="https://www.starryai.com/starrytars?ref=AiHiPUniversity.com"
          rel="external"
          title="Starryai Art Ai Website">
          Starryai Avatar Ai
        </a>
      </li>
    </ul>
    <h2 id="4-coding-ai"><a href="#4-coding-ai">🚀 (4) Coding AI</a></h2>
    <p>
      These are Ai that enhances programmers in their coding. While some generate complete codes and logic, others serve
      as Ai pair programmer.
    </p>
    <ul>
      <li>
        <a
          href="https://openai.com/blog/openai-codex?ref=AiHiPUniversity.com"
          rel="external"
          title="OpenAi Codex Ai Website">
          OpenAi Codex Ai
        </a>
      </li>
      <li>
        <a
          href="https://github.com/features/copilot?ref=AiHiPUniversity.com"
          rel="external"
          title="Github Copilot Ai Website">
          Github Copilot Ai
        </a>
      </li>
    </ul>
    <h2 id="3-text-to-speech-speach-to-text-and-translation-ai">
      <a href="#3-text-to-speech-speach-to-text-and-translation-ai">
        📚 (3) Text To Speech/Speach to Text and Translation AI
      </a>
    </h2>
    <p>This Ai can transcribe audio to text and even translate to/from multiple languages.</p>
    <ul>
      <li>
        <a
          href="https://github.com/openai/whisper?ref=AiHiPUniversity.com"
          rel="external"
          title="OpenAi Whisper Ai Website">
          OpenAi Whisper Ai
        </a>
      </li>
    </ul>
    <h2 id="2-image-generator-ai"><a href="#2-image-generator-ai">🚀 (2) Image Generator AI</a></h2>
    <p>
      These are Ai that can generate realistic images just by following human plain text descriptions of how the image
      should look like.
    </p>
    <p>
      For example, I used one of the Images generating AI called DALL-E to generate the image used for this post above
      by simply describing it in text.
    </p>
    <ul>
      <li>
        <a href="https://labs.openai.com/e?ref=AiHiPUniversity.com" rel="external" title="OpenAi DALL-E Ai Website">
          OpenAi DALL-E Ai
        </a>
      </li>
      <li>
        <a href="https://midjourney.com?ref=AiHiPUniversity.com" rel="external" title="Midjourney Ai Website">
          Midjourney Ai
        </a>
      </li>
    </ul>
    <h2 id="1-text-to-speech-speach-to-text-and-translation-ai">
      <a href="#1-text-to-speech-speach-to-text-and-translation-ai">
        👍 (1) Text To Speech/Speach to Text and Translation AI
      </a>
    </h2>
    <p>These are Ai that can mimic human-like conversation during chat.</p>
    <ul>
      <li>
        <a href="https://chat.openai.com/chat?ref=AiHiPUniversity.com" rel="external" title="OpenAi ChatGPT Ai Website">
          OpenAi ChatGPT Ai
        </a>
      </li>
    </ul>
  </article>
</Post>
