<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <!-- ensures every link below opens in a new tab similar to HTML target="_blank" -->
    <base target="_blank" />

    <h2 id="introduction"><a href="#introduction">✨ INTRODUCTION</a></h2>
    <p>
      In this course, I will be guiding you step by step through how to build and deploy AI powered chatbot like ChatGPT
      using Svelte, Sveltkit (for Frontend), ExpressJs (for Backend) and Openai API.
    </p>
    <p>Then deploy the AI chatbot app to Vercel (Frontend hosting) and Render (Backend hosting) ❤.</p>
    <h3 id="meet-course-instructor"><a href="#meet-course-instructor">🧑‍💻 Meet Course Instructor</a></h3>
    <p>
      <strong>i. Full name</strong>
      :
      <a
        href="https://github.com/SolomonFoskaay?ref=AiHiPUniversity.com"
        rel="external"
        title="Solomon Foskaay Github Profile">
        Solomon Foskaay
      </a>
    </p>
    <p>
      <strong>ii. Experience</strong>
      : 13Years+ in IT (as a Web designer (Wordpress), Digital Marketing &amp; SEO expert, Web3/Crypto Researcher and
      now AI/Game/Metaverse/Web2/Web3 Developer Instructor)
    </p>
    <h3 id="course-prerequisites"><a href="#course-prerequisites">🛂 Course Prerequisites</a></h3>
    <p>Prerequisites for taking this course:</p>
    <p>
      <strong>(1)</strong>
      <a href="https://nodejs.org/en/download?ref=AiHiPUniversity.com" rel="external" title="Nodejs Website">Nodejs</a>
       (Install if not having it yet latest LTS version)
    </p>
    <p>
      <strong>(2)</strong>
      <a href="https://pnpm.io/installation?ref=AiHiPUniversity.com" rel="external" title="PNPM Website">PNPM</a>
       Node package manager preferable over NPM and YARN (Install if not having it yet)
    </p>
    <p>
      <strong>(3)</strong>
       Essential Basic knowledge of:
    </p>
    <ul>
      <li><p>Using CLI</p></li>
      <li><p>Git/Github</p></li>
      <li><p>IDE/Code Editor like Visual Studio Code (VSCode)</p></li>
      <li><p>Svelte/Sveltekit (frontend)</p></li>
      <li><p>ExpressJs (backend)</p></li>
      <li><p>Web Hosting &amp; Domain Hosting</p></li>
    </ul>
    <p>
      <strong>(4)</strong>
       Optional Basic knowledge of:
    </p>
    <ul>
      <li><p>Openai large language AI models and their API</p></li>
      <li><p>Vercel (frontend hosting)</p></li>
      <li><p>Render (backend hosting)</p></li>
    </ul>
    <h3 id="intro-to-aihipuniversity-platform">
      <a href="#intro-to-aihipuniversity-platform">✅ Intro To AiHiPUniversity Platform</a>
    </h3>
    <p>i. Artificial Intelligence + Human Intelligence + Programming = AiHiPUniversity</p>
    <p>ii. Free courses from Beginner, intermediate to Advanced courses for Pro developers.</p>
    <p>iii. Ai 24/7 support to enhance developer productivity</p>
    <p>iv. Support for students in their programming journey</p>
    <p>v. Access to community of like-mind developers across the World.</p>
    <p>vi. Web3/Blockchain development courses</p>
    <p>vii. Free certification (Exercises, Challenges and Final Project is a must to receive certification).</p>
    <h2 id="become-a-successful-developer">
      <a href="#become-a-successful-developer">📝 Become A Successful Developer</a>
    </h2>
    <p>Master essential attitudes to become a lifetime successful developer:</p>
    <p>
      i. Embrace Ai like Foskaay Ai for coding and programming support always (before, during and after launching your
      project)
    </p>
    <p>
      ii. Security (Ai can help discover and patch security flaws in your project early before and during launching)
    </p>
    <p>
      iii. Start every project with Git Private (start with Opensource as beginner dev, close source only when become
      pro dev if essential for funding &amp; IP protection)
    </p>
    <p>iv. Code Commenting</p>
    <p>v. Simplicity wins over complication/complexity (functions getting complex, break to simpler ones)</p>
    <p>vi. Leave local host quicker for Production Deployment and testing.</p>
    <p>vii. Listen to your project users feedbacks and tinker adjustment fast bit-by-bit</p>
    <p>
      viii. Keep the programming spirit high and alive by doing good to humanity and nature with your coding/progamming
      skill and not evil.
    </p>
    <h3 id="course-target-audience"><a href="#course-target-audience">📌 Course Target Audience</a></h3>
    <h4 id="i-who-is-this-course-for"><a href="#i-who-is-this-course-for">i. 👷 Who Is This Course For?</a></h4>
    <ul>
      <li>Intermediate and</li>
      <li>Advanced Developers</li>
    </ul>
    <h4 id="ii-what-you-will-learn-in-this-course">
      <a href="#ii-what-you-will-learn-in-this-course">ii. 📈 What You Will Learn In This Course?</a>
    </h4>
    <p>
      i. At the end of this course, students should have a solid understanding of how to build a chatbot website like
      chatGPT using Svelte/Sveltekit and the OpenAI API.
    </p>
    <p>
      ii. Students will also be able to design and implement an interactive user interface, make API calls and handle
      responses
    </p>
    <p>
      iii. Students will be able to deploy the AI powered chatbot website to a web server and add to your dev profile
      for potential partners, clients, sponsors and employers.
    </p>
    <h2 id="video"><a href="#video">⏪️ VIDEO</a></h2>
    <p>
      If you prefer to watch the video where I guide you on Building &amp; Deploying AI CHATBOT Website Like ChatGPT
      With SVELTE/SVELTEKIT &amp; OpenAI&#39;s GPT-3 API, then below is the full video.
    </p>
    <p>
      <a href="https://www.youtube.com/watch?v=RmiLeS2bEuI&amp;t=905s?ref=AiHiPUniversity.com" rel="external">
        <ImgZoom
          src="/Svelte-SvelteKit-303-Advanced-Build-And-Deploy-Ai-Chatbot-Website/AiHiPU-Vid000001a-7Powerful-Ai-Innovations-That-Will-Change-The-World-In-2023.jpg"
          alt="This a video about Building  &amp; Deploying AI CHATBOT Website Like ChatGPT With SVELTE/SVELTEKIT &amp; OpenAI&#39;s GPT-3 API"
          width="1280"
          height="720" />
      </a>
    </p>
    <p>If not, continue to read the text format.</p>
    <p>
      Though its adviseable to combine the two course materials (Video &amp; text) because some info are not 100%
      converted as text but explained in details in the video).
    </p>
    <h2 id="lesson-1-planning-and-designing">
      <a href="#lesson-1-planning-and-designing">📚 Lesson 1: Planning and Designing</a>
    </h2>
    <p>Planning and Designing the Ai Chatbot with Foskaay AI</p>
    <h3 id="1-planning-the-layout-and-amp-functionality">
      <a href="#1-planning-the-layout-and-amp-functionality">📚 1. Planning the layout &amp; functionality</a>
    </h3>
    <p>Planning the layout and functionality of the AI chatbot interface</p>
    <h3 id="2-designing-the-ui-and-ux"><a href="#2-designing-the-ui-and-ux">📚 2. Designing the UI and UX</a></h3>
    <p>Designing the user interface and user experience</p>
    <h3 id="3-understand-best-practices-building-ai-chatbot">
      <a href="#3-understand-best-practices-building-ai-chatbot">📚 3. Understand best practices building AI Chatbot</a>
    </h3>
    <p>Understanding best practices for building an AI Chatbot</p>
    <h3 id="4-planning-project-folder-structure">
      <a href="#4-planning-project-folder-structure">📚 4. Planning project folder structure</a>
    </h3>
    <p>Planning project folder structure (Backend server and frontend)</p>
    <h3 id="5-deciding-web-development-techstack-to-use">
      <a href="#5-deciding-web-development-techstack-to-use">📚 5. Deciding web development techstack to use</a>
    </h3>
    <h3 id="exercise"><a href="#exercise">📚 Exercise</a></h3>
    <p>Plan and design the chatbot interface and layout. Submit screenshot in your course exercise repo.</p>
    <h4 id="challenge"><a href="#challenge">📚 Challenge</a></h4>
    <p>Research and apply best practices for building an AI Chatbot.</p>
    <h2 id="lesson-2-setup-project-with-git">
      <a href="#lesson-2-setup-project-with-git">🎨 Lesson 2: Setup Project with Git</a>
    </h2>
    <p>These are Ai that generates NFT Arts.</p>
    <ul>
      <li>
        <a
          href="https://starryai.com/create-nft-art-with-artificial-intelligence?ref=AiHiPUniversity.com"
          rel="external"
          title="Starryai Art Ai Website">
          Starryai Art Ai
        </a>
      </li>
    </ul>
    <h2 id="lesson-3-backend-expressjs-with-openai-api">
      <a href="#lesson-3-backend-expressjs-with-openai-api">🔖 Lesson 3: Backend (ExpressJs) With OpenAI API</a>
    </h2>
    <p>Backend (ExpressJs)- Connecting to the OpenAI API With ExpressJs</p>
    <h2 id="lesson-4-frontend-building-the-chatbot-interface">
      <a href="#lesson-4-frontend-building-the-chatbot-interface">
        🔥 Lesson 4: Frontend - Building the Chatbot Interface
      </a>
    </h2>
    <p>Frontend - Building the Chatbot Interface</p>
    <h2 id="lesson-5-adding-security-features-to-ai-chatbot">
      <a href="#lesson-5-adding-security-features-to-ai-chatbot">
        🔒️ Lesson 5: Adding Security Features to AI ChatBot
      </a>
    </h2>
    <p>Adding Security Features to AI ChatBot Website</p>
    <h2 id="lesson-6-deployment-of-chatgpt-like-ai-chatbot">
      <a href="#lesson-6-deployment-of-chatgpt-like-ai-chatbot">🎉 Lesson 6: Deployment of ChatGPT-like Ai Chatbot</a>
    </h2>
    <p>Deployment of ChatGPT-like Ai Chatbot Website to Vercel and Render.</p>
    <h2 id="final-project"><a href="#final-project">🔨 FINAL PROJECT</a></h2>
    <p>
      Build an AI chatbot website using Svelte/Sveltekit and OpenAI&#39;s API. This could be a simple chatbot website or
      more complex chatbot website that uses advanced features such as user account.
    </p>
    <h2 id="certification"><a href="#certification">🦺 CERTIFICATION</a></h2>
    <p>
      Kindly complete all exercises including the challenges and final project in this course to qualify for
      Certificate. Submit the repo containing them for review.
    </p>
    <p>If approved, you will get notification in our discord.</p>
    <p>Aside, that you will also be upgraded on our Discord to course Graduates only discussion private channels.</p>
    <h2 id="course-git-repository"><a href="#course-git-repository">💥 Course Git Repository</a></h2>
    <p>These are Ai that can mimic human-like conversation during chat.</p>
    <ul>
      <li>
        <a href="https://chat.openai.com/chat?ref=AiHiPUniversity.com" rel="external" title="OpenAi ChatGPT Ai Website">
          OpenAi ChatGPT Ai
        </a>
      </li>
    </ul>
    <h2 id="credit-and-amp-referencies"><a href="#credit-and-amp-referencies">👍 Credit &amp; Referencies</a></h2>
  </article>
</Post>
