<!-- auto-generated by QWER -->
<script lang="ts">
  /* eslint-disable @typescript-eslint/ban-ts-comment */
  // @ts-nocheck
  import Post from '$lib/layouts/post.svelte';
  import ImgZoom from '$lib/components/image_zoom.svelte';
  import Video from '$lib/components/video.svelte';
  import CodeCopy from '$lib/components/code_copy.svelte';
  import InfoBox from '$lib/components/info_box.svelte';
</script>

<Post>
  <article slot="post_content">
    <!-- ensures every link below opens in a new tab similar to HTML target="_blank" -->
    <base target="_blank" />

    <p>Welcome To AiHiPUniversity</p>
    <p>We aim to enhance developers with AI to make them more productive.</p>
    <p>Artificial Intelligence + Human Intelligence + Programming = AiHiPUniversity</p>
    <p>Talk To Our Coding Support AI for any programming issues below:</p>
  </article>
</Post>
